if (NOT DEFINED FHB_MODULE_USE_INCLUDE)
    set(FHB_MODULE_USE_INCLUDE OFF)
endif()
set(FHB_MODULE_PATH ${CMAKE_CURRENT_LIST_DIR})
function(fhb_include_module module_dir)
    if (FHB_MODULE_USE_INCLUDE)
        include("${FHB_MODULE_PATH}/${module_dir}/CMakeLists.txt")
    else()
        add_subdirectory("${FHB_MODULE_PATH}/${module_dir}" "${module_dir}")
    endif()
endfunction()
